export const resources = {
    en: {
        translation: {
            HeroDesc: "Create a professional resume effortlessly and",
            HeroSpan: " Free!",
            HeroButton: "Start Building",
            PersonInfoTitle: "Personal Information",
            FirstName: "First Name",
            LastName: "Last Name",
            Email: "Email",
            Phone: "Phone",
            Address: "Address",
            EnterASkill: "Enter a skill",
            Skills: "Skills",
            Job: "Job",
            City: "City",
            Country: "Country",
            License: "License",
            Education: "Education",
            ImageUrl: "Image url",
            Add: "Add",
            Remove: "Remove",
            Company: "Company",
            Role: "Role",
            School: "School",
            Degree: "Degree",
            StartDate: "Start Date",
            EndDate: "End Date",
            Experience: "Experience",
            DeleteResume:"Delete information",
            ResetAll: "Reset all",
            DownloadCv: "Download CV",
        }


    },
    az: {
        translation: {
            HeroDesc: "Peşəkar bir CV-ni asanlıqla və pulsuz yaradın!",
            HeroSpan: "Pulsuz!",
            HeroButton: "Hazırlamağa Başla ",
            PersonInfoTitle: "Şəxsi Məlumat",
            FirstName: "Ad",
            LastName: "Soyad",
            Email: "E-poçt",
            Phone: "Telefon",
            Address: "Ünvan",
            License: "Lisenziya",
            Job: "İş",
            City: "Şəhər",
            Country: "Ölkə",
            Skills: "Bacarıqlar",
            Education: "Təhsil",
            ImageUrl: "Şəkil linki",
            Add: "Əlavə et",
            Remove: "Sil",
            Company: "Şirkət",
            School: "Universitet",
            Degree: "Dərəcə",
            Role: "Vəzifə",
            StartDate: "Başlama tarixi",
            EndDate: "Bitmə tarixi",
            EnterASkill: "Bacarıq daxil edin",
            Experience: "Təcrübə",
            DeleteResume:"Məlumatı Sil",
            ResetAll: "Hamısını sıfırla",
            DownloadCv: "CV yüklə",
        }

    }
}